### ISSUE TITLE
Collaborative editing

### ISSUE THREAD

**Issue by josephluck** [josephluck/internote#183]
https://github.com/ianstormtaylor/slate/issues/259
https://blog.aha.io/text-editor/
https://github.com/humandx/slate-automerge
https://github.com/automerge/automerge
https://stackoverflow.com/questions/31092669/how-does-google-docs-deal-with-editing-collisions

**Comment by Immortalin** [comment]
https://github.com/Immortalin/slate-operational-transform

**Comment by josephluck** [comment]
Thanks @Immortalin - your package looks great!

**Comment by josephluck** [comment]
https://github.com/cudr/slate-collaborative
